services:
  - type: web
    name: telegram-userbot
    runtime: python
    plan: free

    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py

    envVars:
      - key: API_ID
        sync: false
      - key: API_HASH
        sync: false
      - key: SESSION_STRING
        sync: false
      - key: HF_API_TOKEN
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: OPENAI_MODEL
        value: gpt-4.1-mini
      - key: ENABLE_OPENAI_REPLIES
        value: "true"

    autoDeploy: true
